# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d5613c92fc896465729549833307949ebab0e38fd2a02c7aebfcc5da46b24fd8064321ba458764507558d67655e7a6f3c2d14d8dab30b76abd6722eb549cbde

test:
  secret_key_base: 34a496285bf9fa084ba8b9ca532ea72ad27c51181bff4e3740ecfe04a70a8927b05131c0dd64de88ada50fd50239d5eddad7e8a7022804cd9e16d896065ab0ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
